using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Media;

namespace PartageDepense.View
{
    /// <summary>
    /// Produit par IA
    /// Retoune la couleur correspondant à une valeur provenant de l'enum
    /// </summary>
    internal static class Couleur
    {
        public static Color GetColorFromCouleurs(Couleurs Couleurs)
        {
            return Couleurs switch
            {
                Couleurs.AliceBlue => Colors.AliceBlue,
                Couleurs.AntiqueWhite => Colors.AntiqueWhite,
                Couleurs.Aqua => Colors.Aqua,
                Couleurs.Aquamarine => Colors.Aquamarine,
                Couleurs.Azure => Colors.Azure,
                Couleurs.Beige => Colors.Beige,
                Couleurs.Bisque => Colors.Bisque,
                Couleurs.Black => Colors.Black,
                Couleurs.BlanchedAlmond => Colors.BlanchedAlmond,
                Couleurs.Blue => Colors.Blue,
                Couleurs.BlueViolet => Colors.BlueViolet,
                Couleurs.Brown => Colors.Brown,
                Couleurs.BurlyWood => Colors.BurlyWood,
                Couleurs.CadetBlue => Colors.CadetBlue,
                Couleurs.Chartreuse => Colors.Chartreuse,
                Couleurs.Chocolate => Colors.Chocolate,
                Couleurs.Coral => Colors.Coral,
                Couleurs.CornflowerBlue => Colors.CornflowerBlue,
                Couleurs.Cornsilk => Colors.Cornsilk,
                Couleurs.Crimson => Colors.Crimson,
                Couleurs.Cyan => Colors.Cyan,
                Couleurs.DarkBlue => Colors.DarkBlue,
                Couleurs.DarkCyan => Colors.DarkCyan,
                Couleurs.DarkGoldenrod => Colors.DarkGoldenrod,
                Couleurs.DarkGray => Colors.DarkGray,
                Couleurs.DarkGreen => Colors.DarkGreen,
                Couleurs.DarkKhaki => Colors.DarkKhaki,
                Couleurs.DarkMagenta => Colors.DarkMagenta,
                Couleurs.DarkOliveGreen => Colors.DarkOliveGreen,
                Couleurs.DarkOrange => Colors.DarkOrange,
                Couleurs.DarkOrchid => Colors.DarkOrchid,
                Couleurs.DarkRed => Colors.DarkRed,
                Couleurs.DarkSalmon => Colors.DarkSalmon,
                Couleurs.DarkSeaGreen => Colors.DarkSeaGreen,
                Couleurs.DarkSlateBlue => Colors.DarkSlateBlue,
                Couleurs.DarkSlateGray => Colors.DarkSlateGray,
                Couleurs.DarkTurquoise => Colors.DarkTurquoise,
                Couleurs.DarkViolet => Colors.DarkViolet,
                Couleurs.DeepPink => Colors.DeepPink,
                Couleurs.DeepSkyBlue => Colors.DeepSkyBlue,
                Couleurs.DimGray => Colors.DimGray,
                Couleurs.DodgerBlue => Colors.DodgerBlue,
                Couleurs.Firebrick => Colors.Firebrick,
                Couleurs.FloralWhite => Colors.FloralWhite,
                Couleurs.ForestGreen => Colors.ForestGreen,
                Couleurs.Fuchsia => Colors.Fuchsia,
                Couleurs.Gainsboro => Colors.Gainsboro,
                Couleurs.GhostWhite => Colors.GhostWhite,
                Couleurs.Gold => Colors.Gold,
                Couleurs.Goldenrod => Colors.Goldenrod,
                Couleurs.Gray => Colors.Gray,
                Couleurs.Green => Colors.Green,
                Couleurs.GreenYellow => Colors.GreenYellow,
                Couleurs.Honeydew => Colors.Honeydew,
                Couleurs.HotPink => Colors.HotPink,
                Couleurs.IndianRed => Colors.IndianRed,
                Couleurs.Indigo => Colors.Indigo,
                Couleurs.Ivory => Colors.Ivory,
                Couleurs.Khaki => Colors.Khaki,
                Couleurs.Lavender => Colors.Lavender,
                Couleurs.LavenderBlush => Colors.LavenderBlush,
                Couleurs.LawnGreen => Colors.LawnGreen,
                Couleurs.LemonChiffon => Colors.LemonChiffon,
                Couleurs.LightBlue => Colors.LightBlue,
                Couleurs.LightCoral => Colors.LightCoral,
                Couleurs.LightCyan => Colors.LightCyan,
                Couleurs.LightGoldenrodYellow => Colors.LightGoldenrodYellow,
                Couleurs.LightGray => Colors.LightGray,
                Couleurs.LightGreen => Colors.LightGreen,
                Couleurs.LightPink => Colors.LightPink,
                Couleurs.LightSalmon => Colors.LightSalmon,
                Couleurs.LightSeaGreen => Colors.LightSeaGreen,
                Couleurs.LightSkyBlue => Colors.LightSkyBlue,
                Couleurs.LightSlateGray => Colors.LightSlateGray,
                Couleurs.LightSteelBlue => Colors.LightSteelBlue,
                Couleurs.LightYellow => Colors.LightYellow,
                Couleurs.Lime => Colors.Lime,
                Couleurs.LimeGreen => Colors.LimeGreen,
                Couleurs.Linen => Colors.Linen,
                Couleurs.Magenta => Colors.Magenta,
                Couleurs.Maroon => Colors.Maroon,
                Couleurs.MediumAquamarine => Colors.MediumAquamarine,
                Couleurs.MediumBlue => Colors.MediumBlue,
                Couleurs.MediumOrchid => Colors.MediumOrchid,
                Couleurs.MediumPurple => Colors.MediumPurple,
                Couleurs.MediumSeaGreen => Colors.MediumSeaGreen,
                Couleurs.MediumSlateBlue => Colors.MediumSlateBlue,
                Couleurs.MediumSpringGreen => Colors.MediumSpringGreen,
                Couleurs.MediumTurquoise => Colors.MediumTurquoise,
                Couleurs.MediumVioletRed => Colors.MediumVioletRed,
                Couleurs.MidnightBlue => Colors.MidnightBlue,
                Couleurs.MintCream => Colors.MintCream,
                Couleurs.MistyRose => Colors.MistyRose,
                Couleurs.Moccasin => Colors.Moccasin,
                Couleurs.NavajoWhite => Colors.NavajoWhite,
                Couleurs.Navy => Colors.Navy,
                Couleurs.OldLace => Colors.OldLace,
                Couleurs.Olive => Colors.Olive,
                Couleurs.OliveDrab => Colors.OliveDrab,
                Couleurs.Orange => Colors.Orange,
                Couleurs.OrangeRed => Colors.OrangeRed,
                Couleurs.Orchid => Colors.Orchid,
                Couleurs.PaleGoldenrod => Colors.PaleGoldenrod,
                Couleurs.PaleGreen => Colors.PaleGreen,
                Couleurs.PaleTurquoise => Colors.PaleTurquoise,
                Couleurs.PaleVioletRed => Colors.PaleVioletRed,
                Couleurs.PapayaWhip => Colors.PapayaWhip,
                Couleurs.PeachPuff => Colors.PeachPuff,
                Couleurs.Peru => Colors.Peru,
                Couleurs.Pink => Colors.Pink,
                Couleurs.Plum => Colors.Plum,
                Couleurs.PowderBlue => Colors.PowderBlue,
                Couleurs.Purple => Colors.Purple,
                Couleurs.Red => Colors.Red,
                Couleurs.RosyBrown => Colors.RosyBrown,
                Couleurs.RoyalBlue => Colors.RoyalBlue,
                Couleurs.SaddleBrown => Colors.SaddleBrown,
                Couleurs.Salmon => Colors.Salmon,
                Couleurs.SandyBrown => Colors.SandyBrown,
                Couleurs.SeaGreen => Colors.SeaGreen,
                Couleurs.Sienna => Colors.Sienna,
                Couleurs.Silver => Colors.Silver,
                Couleurs.SkyBlue => Colors.SkyBlue,
                Couleurs.SlateBlue => Colors.SlateBlue,
                Couleurs.SlateGray => Colors.SlateGray,
                Couleurs.Snow => Colors.Snow,
                Couleurs.SpringGreen => Colors.SpringGreen,
                Couleurs.SteelBlue => Colors.SteelBlue,
                Couleurs.Tan => Colors.Tan,
                Couleurs.Teal => Colors.Teal,
                Couleurs.Thistle => Colors.Thistle,
                Couleurs.Tomato => Colors.Tomato,
                Couleurs.Turquoise => Colors.Turquoise,
                Couleurs.Violet => Colors.Violet,
                Couleurs.Wheat => Colors.Wheat,
                Couleurs.White => Colors.White,
                Couleurs.WhiteSmoke => Colors.WhiteSmoke,
                Couleurs.Yellow => Colors.Yellow,
                Couleurs.YellowGreen => Colors.YellowGreen,
                _ => throw new ArgumentOutOfRangeException(nameof(Couleurs), Couleurs, null)
            };
        }

        // Obsolete
        //public static Color GetColorFromNom(string couleur)
        //{
        //    return couleur switch
        //    {
        //        "AliceBlue" => Colors.AliceBlue,
        //        "AntiqueWhite" => Colors.AntiqueWhite,
        //        "Aqua" => Colors.Aqua,
        //        "Aquamarine" => Colors.Aquamarine,
        //        "Azure" => Colors.Azure,
        //        "Beige" => Colors.Beige,
        //        "Bisque" => Colors.Bisque,
        //        "Black" => Colors.Black,
        //        "BlanchedAlmond" => Colors.BlanchedAlmond,
        //        "Blue" => Colors.Blue,
        //        "BlueViolet" => Colors.BlueViolet,
        //        "Brown" => Colors.Brown,
        //        "BurlyWood" => Colors.BurlyWood,
        //        "CadetBlue" => Colors.CadetBlue,
        //        "Chartreuse" => Colors.Chartreuse,
        //        "Chocolate" => Colors.Chocolate,
        //        "Coral" => Colors.Coral,
        //        "CornflowerBlue" => Colors.CornflowerBlue,
        //        "Cornsilk" => Colors.Cornsilk,
        //        "Crimson" => Colors.Crimson,
        //        "Cyan" => Colors.Cyan,
        //        "DarkBlue" => Colors.DarkBlue,
        //        "DarkCyan" => Colors.DarkCyan,
        //        "DarkGoldenrod" => Colors.DarkGoldenrod,
        //        "DarkGray" => Colors.DarkGray,
        //        "DarkGreen" => Colors.DarkGreen,
        //        "DarkKhaki" => Colors.DarkKhaki,
        //        "DarkMagenta" => Colors.DarkMagenta,
        //        "DarkOliveGreen" => Colors.DarkOliveGreen,
        //        "DarkOrange" => Colors.DarkOrange,
        //        "DarkOrchid" => Colors.DarkOrchid,
        //        "DarkRed" => Colors.DarkRed,
        //        "DarkSalmon" => Colors.DarkSalmon,
        //        "DarkSeaGreen" => Colors.DarkSeaGreen,
        //        "DarkSlateBlue" => Colors.DarkSlateBlue,
        //        "DarkSlateGray" => Colors.DarkSlateGray,
        //        "DarkTurquoise" => Colors.DarkTurquoise,
        //        "DarkViolet" => Colors.DarkViolet,
        //        "DeepPink" => Colors.DeepPink,
        //        "DeepSkyBlue" => Colors.DeepSkyBlue,
        //        "DimGray" => Colors.DimGray,
        //        "DodgerBlue" => Colors.DodgerBlue,
        //        "Firebrick" => Colors.Firebrick,
        //        "FloralWhite" => Colors.FloralWhite,
        //        "ForestGreen" => Colors.ForestGreen,
        //        "Fuchsia" => Colors.Fuchsia,
        //        "Gainsboro" => Colors.Gainsboro,
        //        "GhostWhite" => Colors.GhostWhite,
        //        "Gold" => Colors.Gold,
        //        "Goldenrod" => Colors.Goldenrod,
        //        "Gray" => Colors.Gray,
        //        "Green" => Colors.Green,
        //        "GreenYellow" => Colors.GreenYellow,
        //        "Honeydew" => Colors.Honeydew,
        //        "HotPink" => Colors.HotPink,
        //        "IndianRed" => Colors.IndianRed,
        //        "Indigo" => Colors.Indigo,
        //        "Ivory" => Colors.Ivory,
        //        "Khaki" => Colors.Khaki,
        //        "Lavender" => Colors.Lavender,
        //        "LavenderBlush" => Colors.LavenderBlush,
        //        "LawnGreen" => Colors.LawnGreen,
        //        "LemonChiffon" => Colors.LemonChiffon,
        //        "LightBlue" => Colors.LightBlue,
        //        "LightCoral" => Colors.LightCoral,
        //        "LightCyan" => Colors.LightCyan,
        //        "LightGoldenrodYellow" => Colors.LightGoldenrodYellow,
        //        "LightGray" => Colors.LightGray,
        //        "LightGreen" => Colors.LightGreen,
        //        "LightPink" => Colors.LightPink,
        //        "LightSalmon" => Colors.LightSalmon,
        //        "LightSeaGreen" => Colors.LightSeaGreen,
        //        "LightSkyBlue" => Colors.LightSkyBlue,
        //        "LightSlateGray" => Colors.LightSlateGray,
        //        "LightSteelBlue" => Colors.LightSteelBlue,
        //        "LightYellow" => Colors.LightYellow,
        //        "Lime" => Colors.Lime,
        //        "LimeGreen" => Colors.LimeGreen,
        //        "Linen" => Colors.Linen,
        //        "Magenta" => Colors.Magenta,
        //        "Maroon" => Colors.Maroon,
        //        "MediumAquamarine" => Colors.MediumAquamarine,
        //        "MediumBlue" => Colors.MediumBlue,
        //        "MediumOrchid" => Colors.MediumOrchid,
        //        "MediumPurple" => Colors.MediumPurple,
        //        "MediumSeaGreen" => Colors.MediumSeaGreen,
        //        "MediumSlateBlue" => Colors.MediumSlateBlue,
        //        "MediumSpringGreen" => Colors.MediumSpringGreen,
        //        "MediumTurquoise" => Colors.MediumTurquoise,
        //        "MediumVioletRed" => Colors.MediumVioletRed,
        //        "MidnightBlue" => Colors.MidnightBlue,
        //        "MintCream" => Colors.MintCream,
        //        "MistyRose" => Colors.MistyRose,
        //        "Moccasin" => Colors.Moccasin,
        //        "NavajoWhite" => Colors.NavajoWhite,
        //        "Navy" => Colors.Navy,
        //        "OldLace" => Colors.OldLace,
        //        "Olive" => Colors.Olive,
        //        "OliveDrab" => Colors.OliveDrab,
        //        "Orange" => Colors.Orange,
        //        "OrangeRed" => Colors.OrangeRed,
        //        "Orchid" => Colors.Orchid,
        //        "PaleGoldenrod" => Colors.PaleGoldenrod,
        //        "PaleGreen" => Colors.PaleGreen,
        //        "PaleTurquoise" => Colors.PaleTurquoise,
        //        "PaleVioletRed" => Colors.PaleVioletRed,
        //        "PapayaWhip" => Colors.PapayaWhip,
        //        "PeachPuff" => Colors.PeachPuff,
        //        "Peru" => Colors.Peru,
        //        "Pink" => Colors.Pink,
        //        "Plum" => Colors.Plum,
        //        "PowderBlue" => Colors.PowderBlue,
        //        "Purple" => Colors.Purple,
        //        "Red" => Colors.Red,
        //        "RosyBrown" => Colors.RosyBrown,
        //        "RoyalBlue" => Colors.RoyalBlue,
        //        "SaddleBrown" => Colors.SaddleBrown,
        //        "Salmon" => Colors.Salmon,
        //        "SandyBrown" => Colors.SandyBrown,
        //        "SeaGreen" => Colors.SeaGreen,
        //        "Sienna" => Colors.Sienna,
        //        "Silver" => Colors.Silver,
        //        "SkyBlue" => Colors.SkyBlue,
        //        "SlateBlue" => Colors.SlateBlue,
        //        "SlateGray" => Colors.SlateGray,
        //        "Snow" => Colors.Snow,
        //        "SpringGreen" => Colors.SpringGreen,
        //        "SteelBlue" => Colors.SteelBlue,
        //        "Tan" => Colors.Tan,
        //        "Teal" => Colors.Teal,
        //        "Thistle" => Colors.Thistle,
        //        "Tomato" => Colors.Tomato,
        //        "Turquoise" => Colors.Turquoise,
        //        "Violet" => Colors.Violet,
        //        "Wheat" => Colors.Wheat,
        //        "White" => Colors.White,
        //        "WhiteSmoke" => Colors.WhiteSmoke,
        //        "Yellow" => Colors.Yellow,
        //        "YellowGreen" => Colors.YellowGreen,
        //        _ => throw new ArgumentOutOfRangeException(nameof(couleur), couleur, null)
        //    };
        //}

    }

    internal enum Couleurs
    {
        AliceBlue,
        AntiqueWhite,
        Aqua,
        Aquamarine,
        Azure,
        Beige,
        Bisque,
        Black,
        BlanchedAlmond,
        Blue,
        BlueViolet,
        Brown,
        BurlyWood,
        CadetBlue,
        Chartreuse,
        Chocolate,
        Coral,
        CornflowerBlue,
        Cornsilk,
        Crimson,
        Cyan,
        DarkBlue,
        DarkCyan,
        DarkGoldenrod,
        DarkGray,
        DarkGreen,
        DarkKhaki,
        DarkMagenta,
        DarkOliveGreen,
        DarkOrange,
        DarkOrchid,
        DarkRed,
        DarkSalmon,
        DarkSeaGreen,
        DarkSlateBlue,
        DarkSlateGray,
        DarkTurquoise,
        DarkViolet,
        DeepPink,
        DeepSkyBlue,
        DimGray,
        DodgerBlue,
        Firebrick,
        FloralWhite,
        ForestGreen,
        Fuchsia,
        Gainsboro,
        GhostWhite,
        Gold,
        Goldenrod,
        Gray,
        Green,
        GreenYellow,
        Honeydew,
        HotPink,
        IndianRed,
        Indigo,
        Ivory,
        Khaki,
        Lavender,
        LavenderBlush,
        LawnGreen,
        LemonChiffon,
        LightBlue,
        LightCoral,
        LightCyan,
        LightGoldenrodYellow,
        LightGray,
        LightGreen,
        LightPink,
        LightSalmon,
        LightSeaGreen,
        LightSkyBlue,
        LightSlateGray,
        LightSteelBlue,
        LightYellow,
        Lime,
        LimeGreen,
        Linen,
        Magenta,
        Maroon,
        MediumAquamarine,
        MediumBlue,
        MediumOrchid,
        MediumPurple,
        MediumSeaGreen,
        MediumSlateBlue,
        MediumSpringGreen,
        MediumTurquoise,
        MediumVioletRed,
        MidnightBlue,
        MintCream,
        MistyRose,
        Moccasin,
        NavajoWhite,
        Navy,
        OldLace,
        Olive,
        OliveDrab,
        Orange,
        OrangeRed,
        Orchid,
        PaleGoldenrod,
        PaleGreen,
        PaleTurquoise,
        PaleVioletRed,
        PapayaWhip,
        PeachPuff,
        Peru,
        Pink,
        Plum,
        PowderBlue,
        Purple,
        Red,
        RosyBrown,
        RoyalBlue,
        SaddleBrown,
        Salmon,
        SandyBrown,
        SeaGreen,
        Sienna,
        Silver,
        SkyBlue,
        SlateBlue,
        SlateGray,
        Snow,
        SpringGreen,
        SteelBlue,
        Tan,
        Teal,
        Thistle,
        Tomato,
        Turquoise,
        Violet,
        Wheat,
        White,
        WhiteSmoke,
        Yellow,
        YellowGreen
    }

}
